import { PDF_TEMPLATE_NAME } from "@/pdf/constants";
import type { InvoicePdfDocument } from "@/pdf/types";

export function InvoicePdfFooter({ document }: { document: InvoicePdfDocument }) {
  const bank = document.business.bankDetails;
  const hasBank =
    Boolean(bank?.accountName?.trim()) ||
    Boolean(bank?.accountNumber?.trim()) ||
    Boolean(bank?.sortCode?.trim());

  return (
    <footer className="invoice-pdf-footer">
      {document.notes ? (
        <section className="invoice-pdf-notes">
          <p className="invoice-pdf-section-label">Note</p>
          <p className="invoice-pdf-notes-copy whitespace-pre-line">{document.notes}</p>
        </section>
      ) : null}

      {hasBank && bank ? (
        <section className="invoice-pdf-notes">
          <p className="invoice-pdf-section-label">Bank details</p>
          <div className="invoice-pdf-notes-copy space-y-1">
            {bank.accountName ? <p>Account Name: {bank.accountName}</p> : null}
            {bank.accountNumber ? (
              <p>Account Number: {bank.accountNumber}</p>
            ) : null}
            {bank.sortCode ? <p>Sort Code: {bank.sortCode}</p> : null}
          </div>
        </section>
      ) : null}

      <div className="invoice-pdf-footer-meta">
        <p>Template: {PDF_TEMPLATE_NAME}</p>
        <p>Generated by SterlingSend</p>
      </div>
    </footer>
  );
}
